### ISSUE TITLE
Should connectors be their in their own package?

### ISSUE THREAD

**Issue by fracek** [auclantis/starknet-react#17]
Web3 React distributes connectors in their own package, while wagmi comes battery included. At the time of writing there is only one connector (Argent X) so it makes sense to include it by default.

What should we do in the future when more connectors become available?

**Comment by tarrencev** [comment]
I think doing something similar to wagmi and providing first party supported connectors and an interface for introducing new ones would be a good approach.

What do you think of providing an interface that matches this?
https://wagmi.sh/guides/connect-wallet

I'd be happy to contribute to modularizing it a bit, so we can introduce new providers without introducing breaking changes in the future.

**Comment by fracek** [comment]
I think that interface looks great. The main difference will be with the `useConnect` hook, let's not use the `[{ data }, action]` return value like wagmi does.

**Comment by fracek** [comment]
Fixed in #51
