### ISSUE TITLE
Documentation Getting Started is wrong

### ISSUE THREAD

**Issue by davisbento** [auclantis/starknet-react#45]
In the documentation: https://auclantis.github.io/starknet-react the **Getting Started** section has a wrong code.

![image](https://user-images.githubusercontent.com/15023064/157288705-a0659f59-6541-4132-909b-838396fdd6e4.png)

And I think it could be nice to have the yarn/npm command sections.

I think it's easy to fix, I'd like to send the PR to fix it?

**Comment by fracek** [comment]
Thank you for spotting this. If you open a PR I will review it.
