### ISSUE TITLE
ConnectorNotFoundError

### ISSUE THREAD

**Issue by hypekn1ght** [auclantis/starknet-react#58]
after running

`npx create-next-app@latest --example https://github.com/auclantis/starknet-react/tree/main/examples/starknet-react-next`

I tried to use the connect button and received ConnectorNotFoundError on the chrome console. 

when I console log the error output from useStarknet, I'd get "could not activate Starknet" any idea what I'm missing here?

**Comment by fracek** [comment]
Fixed in version 0.6.2. Thank you for the report.
